### ISSUE TITLE
CRIT: OpenVPN UDP server not responding

### ISSUE THREAD

**Issue by vilemaxim** [liquidat/nagios-icinga-openvpn#10]
Your script will output that, but exits with a 0 not a 2, so the server says ok.

**Comment by liquidat** [comment]
Dear @vilemaxim, that's strange. If you see a 'CRIT' it is in the right function and thus should return with the return code 2.
Can you try to call the script from command line itself, is the return code still 0? Can you please post the code output?

Also, while it should not change the behavior, you also might want to check the newest upstream version. I just merged ipv6 support.

**Comment by andiwand** [comment]
fixed: https://github.com/liquidat/nagios-icinga-openvpn/pull/12

**Comment by liquidat** [comment]
@andiwand: Ah, I missed the exit code. Of course! Thanks for providing the solution.
