### ISSUE TITLE
Works against HTTP server

### ISSUE THREAD

**Issue by symphorien** [liquidat/nagios-icinga-openvpn#14]
This plugin return OK when checking the port of an HTTP server (in tcp mode), just because, regardless of the query, the HTTP server answers something. That would be nice if this plugin checked whether the data returned fitted the openvpn procol.
A possible use case is to monitor that sslh is working fine.

**Comment by andiwand** [comment]
you could give #16 a try!

**Comment by liquidat** [comment]
@symphorien Can you please check if #16 solves that?

**Comment by andiwand** [comment]
for me:
`$ ./check_openvpn -p 443 -t boran.bayz.de 
CRIT: Invalid response`
